### ISSUE TITLE
[Bug] Crash when opening a recipe

### ISSUE THREAD

**Issue by AntiGuide** [vishnuraghavb/EnRecipes#107]
**Describe the bug**
The app crashes when opening any of my recipes

**To Reproduce**
1. Open the app
2. Open any recipe
3. App crashes

**Expected behavior**
Display my recipe

**Device information (please complete the following information):**
 - Android Version: 9
 - EnRecipes Version(as in app's about page):  2.0.2

**Additional context**
ADB log
```
10-26 15:48:30.828 23373 23373 E AndroidRuntime: FATAL EXCEPTION: main
10-26 15:48:30.828 23373 23373 E AndroidRuntime: Process: com.vishnuraghav.EnRecipes, PID: 23373
10-26 15:48:30.828 23373 23373 E AndroidRuntime: com.tns.NativeScriptException: Calling js method onCreateView failed
10-26 15:48:30.828 23373 23373 E AndroidRuntime: TypeError: t.split is not a function
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:205)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6991)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-26 15:48:30.828 23373 23373 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by vishnuraghavb** [comment]
@AntiGuide This was a known issue and only occurs on the f-droid release (v2.0.1) because of my mistake, later it was fixed on v2.0.2. In order open the recipes and fix the issue on your end, please install v2.0.2 (if done already, clear app data under settings) and reimport the backup file exported from v2.0.0. Thanks.
